void tests();
void test_tokens();
void test_newLexer();
void test_charLexed();
void test_matchString();
void test_lexBool();
void test_lexCharacter();
void test_lexNumber();
void test_lexMultipleValues();
