void matchString(Lexer *lexer, char *str);
// bool oneOf(char c, char *str);
void matchDelimiter(Lexer *lexer);
void matchDelimitedString(Lexer *lexer, char *string);
bool lexComment(Lexer *lexer);
bool lexSpaces(Lexer *lexer);
void lexBoolean(Lexer *lexer);
void lexSingleCharacter(Lexer *lexer);
void lexCharacter(Lexer *lexer);
int lexSign(Lexer *lexer);
int lexDigits(Lexer *lexer);
void lexNumber(Lexer *lexer);
void lexPeculiarIdentifier(Lexer *lexer);
void lexIdentifier(Lexer *lexer);
void lexSingleCharToken(Lexer *lexer, char match, SimpleToken SIMPLE_TOKEN);
void lexSingleToken(Lexer *lexer);
void lexIntertokenSpace(Lexer *lexer);
void lexAllInput(Lexer *lexer);
